global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
    - targets: ["16.171.148.23:8081"]
  - job_name: 'loki'
    static_configs:
      - targets: ['16.171.148.23:3100']
        labels:
          job: 'loki'
root@ip-172-31-44-172:~/monitor/prometheus# cat alertmanager.yml
global:
  resolve_timeout: 1m


route:
  receiver: 'gmail-receiver'
  repeat_interval: 1m
receivers:
- name: gmail-receiver
  email_configs:
  - to: yapadinithi@gmail.com
    from: yapadinithi@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: yapadinithi@gmail.com
    auth_identity: yapadinithi@gmail.com
    auth_password: cytk cspu ddib sbrw
